name: ABC Schoolhouse
favicon: null
layout_spectrum: 0.28908062796108425
typography_spectrum: 0.31046472513116896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fdfe'
    - '#a8e256'
    - '#e50028'
    - '#742c31'
    - '#4d8fcc'
  brandStrength: 0.625
  lightness: 0.5617285252083093
  saturation: 0.006130805471912026
  rhythmicContrast: 0.47604522900655866
purpose: []
